export interface Theme {
  id: string
  name: string
  nameEn: string
  description: string
  icon: string
  colors: {
    primary: string
    primaryDark: string
    primaryLight: string
    secondary: string
    accent: string
    background: string
    backgroundDark: string
    surface: string
    surfaceDark: string
    text: string
    textDark: string
    textMuted: string
  }
  gradient: string
  fontFamily: string
  borderRadius: string
  shadow: 'soft' | 'sharp' | 'elevated'
}

export const themes: Theme[] = [
  {
    id: 'totoro',
    name: '龙猫森林',
    nameEn: 'Totoro Forest',
    description: '清新自然的森林色调，灵感来自宫崎骏的龙猫',
    icon: '🌿',
    colors: {
      primary: '#4F836B',
      primaryDark: '#3D6B55',
      primaryLight: '#8FB8A8',
      secondary: '#6A9C89',
      accent: '#EB4F85',
      background: '#F0F7F4',
      backgroundDark: '#1A202C',
      surface: '#FFFFFF',
      surfaceDark: '#2D3748',
      text: '#1A202C',
      textDark: '#F7FAFC',
      textMuted: '#718096',
    },
    gradient: 'linear-gradient(135deg, #4F836B 0%, #3D6B55 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'soft',
  },
  {
    id: 'sakura',
    name: '樱花粉',
    nameEn: 'Sakura Pink',
    description: '温柔的樱花粉色，浪漫而优雅',
    icon: '🌸',
    colors: {
      primary: '#FFB7C5',
      primaryDark: '#FF9EB5',
      primaryLight: '#FFD9E3',
      secondary: '#FF8FA3',
      accent: '#FF6B8B',
      background: '#FFF5F8',
      backgroundDark: '#1A1A2E',
      surface: '#FFFFFF',
      surfaceDark: '#2D2D44',
      text: '#2D2D44',
      textDark: '#FFF5F8',
      textMuted: '#9999AA',
    },
    gradient: 'linear-gradient(135deg, #FFB7C5 0%, #FF8FA3 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'soft',
  },
  {
    id: 'ocean',
    name: '深海蓝',
    nameEn: 'Deep Ocean',
    description: '深邃的海洋蓝色，沉稳而专业',
    icon: '🌊',
    colors: {
      primary: '#1E5F74',
      primaryDark: '#154555',
      primaryLight: '#5DA9B9',
      secondary: '#3A889B',
      accent: '#F4A261',
      background: '#E8F4F8',
      backgroundDark: '#0D1B2A',
      surface: '#FFFFFF',
      surfaceDark: '#1B3A4B',
      text: '#0D1B2A',
      textDark: '#E8F4F8',
      textMuted: '#5A7A8A',
    },
    gradient: 'linear-gradient(135deg, #1E5F74 0%, #3A889B 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'elevated',
  },
  {
    id: 'sunset',
    name: '落日橙',
    nameEn: 'Sunset Orange',
    description: '温暖的落日橙色，充满活力',
    icon: '🌅',
    colors: {
      primary: '#F4A261',
      primaryDark: '#E76F51',
      primaryLight: '#FFCDA3',
      secondary: '#E9C46A',
      accent: '#2A9D8F',
      background: '#FFF8F0',
      backgroundDark: '#1E1A17',
      surface: '#FFFFFF',
      surfaceDark: '#2D2622',
      text: '#1E1A17',
      textDark: '#FFF8F0',
      textMuted: '#8A7A6A',
    },
    gradient: 'linear-gradient(135deg, #F4A261 0%, #E76F51 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'soft',
  },
  {
    id: 'lavender',
    name: '薰衣草紫',
    nameEn: 'Lavender Purple',
    description: '优雅的薰衣草紫色，梦幻而宁静',
    icon: '💜',
    colors: {
      primary: '#9B7EBD',
      primaryDark: '#7B5FA3',
      primaryLight: '#C4A8D9',
      secondary: '#B088D1',
      accent: '#FFD93D',
      background: '#F5F0FA',
      backgroundDark: '#1A1520',
      surface: '#FFFFFF',
      surfaceDark: '#2D2633',
      text: '#1A1520',
      textDark: '#F5F0FA',
      textMuted: '#7A6A8A',
    },
    gradient: 'linear-gradient(135deg, #9B7EBD 0%, #7B5FA3 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'soft',
  },
  {
    id: 'mint',
    name: '薄荷绿',
    nameEn: 'Mint Green',
    description: '清爽的薄荷绿色，清新怡人',
    icon: '🍃',
    colors: {
      primary: '#5DBAA8',
      primaryDark: '#4A9A8A',
      primaryLight: '#9AD5C8',
      secondary: '#7BC9B8',
      accent: '#FF6B6B',
      background: '#F0FAF8',
      backgroundDark: '#1A201E',
      surface: '#FFFFFF',
      surfaceDark: '#26302E',
      text: '#1A201E',
      textDark: '#F0FAF8',
      textMuted: '#6A7A75',
    },
    gradient: 'linear-gradient(135deg, #5DBAA8 0%, #4A9A8A 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'soft',
  },
  {
    id: 'midnight',
    name: '午夜黑',
    nameEn: 'Midnight Black',
    description: '神秘的午夜黑色，极简而高级',
    icon: '🌙',
    colors: {
      primary: '#2D3436',
      primaryDark: '#1A2022',
      primaryLight: '#5A6365',
      secondary: '#4A5254',
      accent: '#FDCB6E',
      background: '#F8F9FA',
      backgroundDark: '#0D1011',
      surface: '#FFFFFF',
      surfaceDark: '#1F2426',
      text: '#0D1011',
      textDark: '#F8F9FA',
      textMuted: '#6A7274',
    },
    gradient: 'linear-gradient(135deg, #2D3436 0%, #1A2022 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '8px',
    shadow: 'sharp',
  },
  {
    id: 'coral',
    name: '珊瑚红',
    nameEn: 'Coral Red',
    description: '热情的珊瑚红色，温暖而充满活力',
    icon: '🔥',
    colors: {
      primary: '#FF6B6B',
      primaryDark: '#EE5A5A',
      primaryLight: '#FF9E9E',
      secondary: '#FF8E8E',
      accent: '#4ECDC4',
      background: '#FFF5F5',
      backgroundDark: '#1E1515',
      surface: '#FFFFFF',
      surfaceDark: '#2D2222',
      text: '#1E1515',
      textDark: '#FFF5F5',
      textMuted: '#8A7272',
    },
    gradient: 'linear-gradient(135deg, #FF6B6B 0%, #EE5A5A 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'soft',
  },
  {
    id: 'sky',
    name: '天空蓝',
    nameEn: 'Sky Blue',
    description: '明亮的天空蓝色，开阔而自由',
    icon: '☁️',
    colors: {
      primary: '#5DA9E9',
      primaryDark: '#4A8AD9',
      primaryLight: '#9BC5F0',
      secondary: '#7AB8EB',
      accent: '#FFD93D',
      background: '#F0F8FF',
      backgroundDark: '#151A20',
      surface: '#FFFFFF',
      surfaceDark: '#222A33',
      text: '#151A20',
      textDark: '#F0F8FF',
      textMuted: '#6A7580',
    },
    gradient: 'linear-gradient(135deg, #5DA9E9 0%, #4A8AD9 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'soft',
  },
  {
    id: 'forest',
    name: '森林绿',
    nameEn: 'Forest Green',
    description: '浓郁的森林绿色，自然而稳重',
    icon: '🌲',
    colors: {
      primary: '#2D5A3D',
      primaryDark: '#1E3D29',
      primaryLight: '#5A8F6B',
      secondary: '#3D7A52',
      accent: '#D4A574',
      background: '#F0F5F2',
      backgroundDark: '#0F1A12',
      surface: '#FFFFFF',
      surfaceDark: '#1A2A20',
      text: '#0F1A12',
      textDark: '#F0F5F2',
      textMuted: '#5A6A5F',
    },
    gradient: 'linear-gradient(135deg, #2D5A3D 0%, #1E3D29 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'elevated',
  },
]

export const defaultTheme = themes[0]

export function getThemeById(id: string): Theme {
  return themes.find(t => t.id === id) || defaultTheme
}
