// 10 套高级感主题配置

export interface Theme {
  id: string
  name: string
  nameEn: string
  description: string
  icon: string
  colors: {
    primary: string
    primaryDark: string
    primaryLight: string
    secondary: string
    accent: string
    background: string
    backgroundDark: string
    surface: string
    surfaceDark: string
    text: string
    textDark: string
    textMuted: string
  }
  gradient: string
  fontFamily: string
  borderRadius: string
  shadow: 'soft' | 'sharp' | 'elevated'
}

export const themes: Theme[] = [
  {
    id: 'totoro',
    name: '龙猫森林',
    nameEn: 'Totoro Forest',
    description: '清新自然的森林色调，灵感来自宫崎骏的龙猫',
    icon: '🌿',
    colors: {
      primary: '#4F836B',
      primaryDark: '#3D6B55',
      primaryLight: '#8FB8A8',
      secondary: '#6A9C89',
      accent: '#EB4F85',
      background: '#F0F7F4',
      backgroundDark: '#1A202C',
      surface: '#FFFFFF',
      surfaceDark: '#2D3748',
      text: '#1A202C',
      textDark: '#F7FAFC',
      textMuted: '#718096',
    },
    gradient: 'linear-gradient(135deg, #4F836B 0%, #3D6B55 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '12px',
    shadow: 'soft',
  },
  {
    id: 'midnight',
    name: '午夜蓝调',
    nameEn: 'Midnight Blue',
    description: '深邃优雅的蓝黑色调，适合夜间阅读',
    icon: '🌙',
    colors: {
      primary: '#6366F1',
      primaryDark: '#4F46E5',
      primaryLight: '#818CF8',
      secondary: '#8B5CF6',
      accent: '#EC4899',
      background: '#0F172A',
      backgroundDark: '#020617',
      surface: '#1E293B',
      surfaceDark: '#334155',
      text: '#F1F5F9',
      textDark: '#F8FAFC',
      textMuted: '#94A3B8',
    },
    gradient: 'linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%)',
    fontFamily: 'Lexend, system-ui',
    borderRadius: '8px',
    shadow: 'elevated',
  },
  {
    id: 'sunset',
    name: '落日余晖',
    nameEn: 'Sunset Glow',
    description: '温暖浪漫的橙红色调，如落日般温暖',
    icon: '🌅',
    colors: {
      primary: '#F97316',
      primaryDark: '#EA580C',
      primaryLight: '#FB923C',
      secondary: '#EC4899',
      accent: '#8B5CF6',
      background: '#FFF7ED',
      backgroundDark: '#1C1917',
      surface: '#FFFFFF',
      surfaceDark: '#292524',
      text: '#1C1917',
      textDark: '#FAFAF9',
      textMuted: '#78716C',
    },
    gradient: 'linear-gradient(135deg, #F97316 0%, #EC4899 100%)',
    fontFamily: 'Plus Jakarta Sans, system-ui',
    borderRadius: '16px',
    shadow: 'soft',
  },
  {
    id: 'arctic',
    name: '极地冰川',
    nameEn: 'Arctic Ice',
    description: '清冷纯净的蓝白色调，极简主义风格',
    icon: '❄️',
    colors: {
      primary: '#0EA5E9',
      primaryDark: '#0284C7',
      primaryLight: '#38BDF8',
      secondary: '#14B8A6',
      accent: '#6366F1',
      background: '#F0F9FF',
      backgroundDark: '#0C1929',
      surface: '#FFFFFF',
      surfaceDark: '#1E3A5F',
      text: '#0C1929',
      textDark: '#F0F9FF',
      textMuted: '#64748B',
    },
    gradient: 'linear-gradient(135deg, #0EA5E9 0%, #14B8A6 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '4px',
    shadow: 'sharp',
  },
  {
    id: 'sakura',
    name: '樱花飞舞',
    nameEn: 'Sakura Bloom',
    description: '温柔浪漫的粉色调，春日樱花般梦幻',
    icon: '🌸',
    colors: {
      primary: '#EC4899',
      primaryDark: '#DB2777',
      primaryLight: '#F472B6',
      secondary: '#F97316',
      accent: '#8B5CF6',
      background: '#FDF2F8',
      backgroundDark: '#2D1B2E',
      surface: '#FFFFFF',
      surfaceDark: '#4C1D95',
      text: '#831843',
      textDark: '#FCE7F3',
      textMuted: '#BE185D',
    },
    gradient: 'linear-gradient(135deg, #EC4899 0%, #F472B6 100%)',
    fontFamily: 'Noto Sans JP, system-ui',
    borderRadius: '20px',
    shadow: 'soft',
  },
  {
    id: 'emerald',
    name: '翡翠绿洲',
    nameEn: 'Emerald Oasis',
    description: '高贵典雅的绿色调，奢华而不失内涵',
    icon: '💎',
    colors: {
      primary: '#10B981',
      primaryDark: '#059669',
      primaryLight: '#34D399',
      secondary: '#0EA5E9',
      accent: '#F59E0B',
      background: '#ECFDF5',
      backgroundDark: '#022C22',
      surface: '#FFFFFF',
      surfaceDark: '#064E3B',
      text: '#064E3B',
      textDark: '#ECFDF5',
      textMuted: '#059669',
    },
    gradient: 'linear-gradient(135deg, #10B981 0%, #059669 100%)',
    fontFamily: 'Playfair Display, system-ui',
    borderRadius: '8px',
    shadow: 'elevated',
  },
  {
    id: 'monochrome',
    name: '极简黑白',
    nameEn: 'Minimal Mono',
    description: '经典永恒的黑白色调，永恒的高级感',
    icon: '⚫',
    colors: {
      primary: '#18181B',
      primaryDark: '#09090B',
      primaryLight: '#3F3F46',
      secondary: '#71717A',
      accent: '#18181B',
      background: '#FAFAFA',
      backgroundDark: '#09090B',
      surface: '#FFFFFF',
      surfaceDark: '#18181B',
      text: '#18181B',
      textDark: '#FAFAFA',
      textMuted: '#71717A',
    },
    gradient: 'linear-gradient(135deg, #18181B 0%, #71717A 100%)',
    fontFamily: 'Inter, system-ui',
    borderRadius: '0px',
    shadow: 'sharp',
  },
  {
    id: 'ocean',
    name: '深海秘境',
    nameEn: 'Deep Ocean',
    description: '神秘深邃的蓝色调，如深海般迷人',
    icon: '🌊',
    colors: {
      primary: '#0369A1',
      primaryDark: '#075985',
      primaryLight: '#0EA5E9',
      secondary: '#0D9488',
      accent: '#F59E0B',
      background: '#F0F9FF',
      backgroundDark: '#0C4A6E',
      surface: '#FFFFFF',
      surfaceDark: '#164E63',
      text: '#0C4A6E',
      textDark: '#E0F2FE',
      textMuted: '#0284C7',
    },
    gradient: 'linear-gradient(135deg, #0369A1 0%, #0D9488 100%)',
    fontFamily: 'Cabin, system-ui',
    borderRadius: '12px',
    shadow: 'elevated',
  },
  {
    id: 'amber',
    name: '琥珀流光',
    nameEn: 'Amber Glow',
    description: '温暖华丽的金棕色调，复古而优雅',
    icon: '🍯',
    colors: {
      primary: '#D97706',
      primaryDark: '#B45309',
      primaryLight: '#FBBF24',
      secondary: '#92400E',
      accent: '#DC2626',
      background: '#FFFBEB',
      backgroundDark: '#451A03',
      surface: '#FFFFFF',
      surfaceDark: '#78350F',
      text: '#451A03',
      textDark: '#FEF3C7',
      textMuted: '#92400E',
    },
    gradient: 'linear-gradient(135deg, #D97706 0%, #B45309 100%)',
    fontFamily: 'Merriweather, system-ui',
    borderRadius: '8px',
    shadow: 'soft',
  },
  {
    id: 'cyberpunk',
    name: '赛博朋克',
    nameEn: 'Cyberpunk',
    description: '未来科技感的霓虹色调，前卫大胆',
    icon: '🤖',
    colors: {
      primary: '#EC4899',
      primaryDark: '#DB2777',
      primaryLight: '#F472B6',
      secondary: '#8B5CF6',
      accent: '#06B6D4',
      background: '#09090B',
      backgroundDark: '#000000',
      surface: '#18181B',
      surfaceDark: '#27272A',
      text: '#FAFAFA',
      textDark: '#FFFFFF',
      textMuted: '#A1A1AA',
    },
    gradient: 'linear-gradient(135deg, #EC4899 0%, #8B5CF6 100%)',
    fontFamily: 'Rajdhani, system-ui',
    borderRadius: '4px',
    shadow: 'sharp',
  },
]

export const defaultTheme = themes[0]

export function getThemeById(id: string): Theme {
  return themes.find(t => t.id === id) || defaultTheme
}
