// 易经 64 卦完整数据
// 包含全部 64 卦的卦辞、象传、爻辞（传统易经原文）

export interface Hexagram {
  id: number
  number: number
  name: string
  pinyin: string
  character: string
  structure: number[]
  trigrams: {
    upper: string
    lower: string
  }
  judgment: string
  image: string
  lines: LineInterpretation[]
}

export interface LineInterpretation {
  position: number
  text: string
}

export const TRIGRAMS = {
  qian: { name: '乾', element: '天', attribute: '健' },
  kun: { name: '坤', element: '地', attribute: '顺' },
  zhen: { name: '震', element: '雷', attribute: '动' },
  xun: { name: '巽', element: '风', attribute: '入' },
  kan: { name: '坎', element: '水', attribute: '陷' },
  li: { name: '离', element: '火', attribute: '丽' },
  gen: { name: '艮', element: '山', attribute: '止' },
  dui: { name: '兑', element: '泽', attribute: '悦' },
}

export const HEXAGRAMS: Hexagram[] = [
  {
    id: 1,
    number: 1,
    name: '乾',
    pinyin: 'qián',
    character: '䷀',
    structure: [1, 1, 1, 1, 1, 1],
    trigrams: { upper: 'qian', lower: 'qian' },
    judgment: '元亨利贞。',
    image: '天行健，君子以自强不息。',
    lines: [
      { position: 1, text: '潜龙勿用。' },
      { position: 2, text: '见龙在田，利见大人。' },
      { position: 3, text: '君子终日乾乾，夕惕若厉，无咎。' },
      { position: 4, text: '或跃在渊，无咎。' },
      { position: 5, text: '飞龙在天，利见大人。' },
      { position: 6, text: '亢龙有悔。' },
    ],
  },
  {
    id: 2,
    number: 2,
    name: '坤',
    pinyin: 'kūn',
    character: '䷁',
    structure: [0, 0, 0, 0, 0, 0],
    trigrams: { upper: 'kun', lower: 'kun' },
    judgment: '元亨，利牝马之贞。君子有攸往，先迷后得主。利西南得朋，东北丧朋。安贞吉。',
    image: '地势坤，君子以厚德载物。',
    lines: [
      { position: 1, text: '履霜，坚冰至。' },
      { position: 2, text: '直方大，不习无不利。' },
      { position: 3, text: '含章可贞。或从王事，无成有终。' },
      { position: 4, text: '括囊，无咎无誉。' },
      { position: 5, text: '黄裳，元吉。' },
      { position: 6, text: '龙战于野，其血玄黄。' },
    ],
  },
  {
    id: 3,
    number: 3,
    name: '屯',
    pinyin: 'zhūn',
    character: '䷂',
    structure: [1, 0, 0, 0, 1, 0],
    trigrams: { upper: 'kan', lower: 'zhen' },
    judgment: '元亨利贞。勿用有攸往，利建侯。',
    image: '云雷，屯。君子以经纶。',
    lines: [
      { position: 1, text: '磐桓，利居贞，利建侯。' },
      { position: 2, text: '屯如邅如，乘马班如。匪寇婚媾，女子贞不字，十年乃字。' },
      { position: 3, text: '即鹿无虞，惟入于林中。君子几不如舍，往吝。' },
      { position: 4, text: '乘马班如，求婚媾，往吉，无不利。' },
      { position: 5, text: '屯其膏，小贞吉，大贞凶。' },
      { position: 6, text: '乘马班如，泣血涟如。' },
    ],
  },
  {
    id: 4,
    number: 4,
    name: '蒙',
    pinyin: 'méng',
    character: '䷃',
    structure: [0, 1, 0, 0, 0, 1],
    trigrams: { upper: 'gen', lower: 'kan' },
    judgment: '亨。匪我求童蒙，童蒙求我。初筮告，再三渎，渎则不告。利贞。',
    image: '山下出泉，蒙。君子以果行育德。',
    lines: [
      { position: 1, text: '发蒙，利用刑人，用说桎梏，以往吝。' },
      { position: 2, text: '包蒙吉，纳妇吉，子克家。' },
      { position: 3, text: '勿用取女，见金夫，不有躬，无攸利。' },
      { position: 4, text: '困蒙，吝。' },
      { position: 5, text: '童蒙，吉。' },
      { position: 6, text: '击蒙，不利为寇，利御寇。' },
    ],
  },
  {
    id: 5,
    number: 5,
    name: '需',
    pinyin: 'xū',
    character: '䷄',
    structure: [1, 1, 0, 1, 0, 0],
    trigrams: { upper: 'kan', lower: 'qian' },
    judgment: '有孚，光亨，贞吉。利涉大川。',
    image: '云上于天，需。君子以饮食宴乐。',
    lines: [
      { position: 1, text: '需于郊，利用恒，无咎。' },
      { position: 2, text: '需于沙，小有言，终吉。' },
      { position: 3, text: '需于泥，致寇至。' },
      { position: 4, text: '需于血，出自穴。' },
      { position: 5, text: '需于酒食，贞吉。' },
      { position: 6, text: '入于穴，有不速之客三人来，敬之终吉。' },
    ],
  },
  {
    id: 6,
    number: 6,
    name: '讼',
    pinyin: 'sòng',
    character: '䷅',
    structure: [0, 1, 1, 1, 0, 0],
    trigrams: { upper: 'qian', lower: 'kan' },
    judgment: '有孚窒惕，中吉，终凶。利见大人，不利涉大川。',
    image: '天与水违行，讼。君子以作事谋始。',
    lines: [
      { position: 1, text: '不永所事，小有言，终吉。' },
      { position: 2, text: '不克讼，归而逋，其邑人三百户，无眚。' },
      { position: 3, text: '食旧德，贞厉，终吉。或从王事，无成。' },
      { position: 4, text: '不克讼，复即命渝，安贞吉。' },
      { position: 5, text: '讼，元吉。' },
      { position: 6, text: '或锡之鞶带，终朝三褫之。' },
    ],
  },
  {
    id: 7,
    number: 7,
    name: '师',
    pinyin: 'shī',
    character: '䷆',
    structure: [0, 1, 0, 0, 0, 0],
    trigrams: { upper: 'kun', lower: 'kan' },
    judgment: '贞，丈人吉，无咎。',
    image: '地中有水，师。君子以容民畜众。',
    lines: [
      { position: 1, text: '师出以律，否臧凶。' },
      { position: 2, text: '在师中，吉无咎，王三锡命。' },
      { position: 3, text: '师或舆尸，凶。' },
      { position: 4, text: '师左次，无咎。' },
      { position: 5, text: '田有禽，利执言，无咎。长子帅师，弟子舆尸，贞凶。' },
      { position: 6, text: '大君有命，开国承家，小人勿用。' },
    ],
  },
  {
    id: 8,
    number: 8,
    name: '比',
    pinyin: 'bǐ',
    character: '䷇',
    structure: [0, 0, 0, 0, 1, 0],
    trigrams: { upper: 'kan', lower: 'kun' },
    judgment: '吉。原筮元永贞，无咎。不宁方来，后夫凶。',
    image: '地上有水，比。先王以建万国，亲诸侯。',
    lines: [
      { position: 1, text: '有孚比之，无咎。有孚盈缶，终来有它，吉。' },
      { position: 2, text: '比之自内，贞吉。' },
      { position: 3, text: '比之匪人。' },
      { position: 4, text: '外比之，贞吉。' },
      { position: 5, text: '显比，王用三驱，失前禽。邑人不诫，吉。' },
      { position: 6, text: '比之无首，凶。' },
    ],
  },
  {
    id: 9,
    number: 9,
    name: '小畜',
    pinyin: 'xiǎo chù',
    character: '䷈',
    structure: [1, 1, 1, 0, 1, 1],
    trigrams: { upper: 'xun', lower: 'qian' },
    judgment: '亨。密云不雨，自我西郊。',
    image: '风行天上，小畜。君子以懿文德。',
    lines: [
      { position: 1, text: '复自道，何其咎？吉。' },
      { position: 2, text: '牵复，吉。' },
      { position: 3, text: '舆说辐，夫妻反目。' },
      { position: 4, text: '有孚，血去惕出，无咎。' },
      { position: 5, text: '有孚挛如，富以其邻。' },
      { position: 6, text: '既雨既处，尚德载，妇贞厉。月几望，君子征凶。' },
    ],
  },
  {
    id: 10,
    number: 10,
    name: '履',
    pinyin: 'lǚ',
    character: '䷉',
    structure: [1, 1, 0, 1, 1, 1],
    trigrams: { upper: 'qian', lower: 'dui' },
    judgment: '履虎尾，不咥人，亨。',
    image: '上天下泽，履。君子以辨上下，定民志。',
    lines: [
      { position: 1, text: '素履，往无咎。' },
      { position: 2, text: '履道坦坦，幽人贞吉。' },
      { position: 3, text: '眇能视，跛能履，履虎尾，咥人，凶。武人为于大君。' },
      { position: 4, text: '履虎尾，愬愬，终吉。' },
      { position: 5, text: '夬履，贞厉。' },
      { position: 6, text: '视履考祥，其旋元吉。' },
    ],
  },
  {
    id: 11,
    number: 11,
    name: '泰',
    pinyin: 'tài',
    character: '䷊',
    structure: [1, 1, 1, 0, 0, 0],
    trigrams: { upper: 'kun', lower: 'qian' },
    judgment: '小往大来，吉亨。',
    image: '天地交，泰。后以财成天地之道，辅相天地之宜，以左右民。',
    lines: [
      { position: 1, text: '拔茅茹，以其汇，征吉。' },
      { position: 2, text: '包荒，用冯河，不遐遗，朋亡，得尚于中行。' },
      { position: 3, text: '无平不陂，无往不复。艰贞无咎。勿恤其孚，于食有福。' },
      { position: 4, text: '翩翩，不富，以其邻，不戒以孚。' },
      { position: 5, text: '帝乙归妹，以祉元吉。' },
      { position: 6, text: '城复于隍，勿用师。自邑告命，贞吝。' },
    ],
  },
  {
    id: 12,
    number: 12,
    name: '否',
    pinyin: 'pǐ',
    character: '䷋',
    structure: [0, 0, 0, 1, 1, 1],
    trigrams: { upper: 'qian', lower: 'kun' },
    judgment: '否之匪人，不利君子贞，大往小来。',
    image: '天地不交，否。君子以俭德辟难，不可荣以禄。',
    lines: [
      { position: 1, text: '拔茅茹，以其汇，贞吉亨。' },
      { position: 2, text: '包承。小人吉，大人否，亨。' },
      { position: 3, text: '包羞。' },
      { position: 4, text: '有命无咎，畴离祉。' },
      { position: 5, text: '休否，大人吉。其亡其亡，系于苞桑。' },
      { position: 6, text: '倾否，先否后喜。' },
    ],
  },
  {
    id: 13,
    number: 13,
    name: '同人',
    pinyin: 'tóng rén',
    character: '䷌',
    structure: [1, 0, 1, 1, 1, 1],
    trigrams: { upper: 'qian', lower: 'li' },
    judgment: '同人于野，亨。利涉大川，利君子贞。',
    image: '天与火，同人。君子以类族辨物。',
    lines: [
      { position: 1, text: '同人于门，无咎。' },
      { position: 2, text: '同人于宗，吝。' },
      { position: 3, text: '伏戎于莽，升其高陵，三岁不兴。' },
      { position: 4, text: '乘其墉，弗克攻，吉。' },
      { position: 5, text: '同人，先号啕而后笑。大师克相遇。' },
      { position: 6, text: '同人于郊，无悔。' },
    ],
  },
  {
    id: 14,
    number: 14,
    name: '大有',
    pinyin: 'dà yǒu',
    character: '䷍',
    structure: [1, 1, 1, 0, 1, 1],
    trigrams: { upper: 'li', lower: 'qian' },
    judgment: '元亨。',
    image: '火在天上，大有。君子以遏恶扬善，顺天休命。',
    lines: [
      { position: 1, text: '无交害，匪咎，艰则无咎。' },
      { position: 2, text: '大车以载，有攸往，无咎。' },
      { position: 3, text: '公用亨于天子，小人弗克。' },
      { position: 4, text: '匪其彭，无咎。' },
      { position: 5, text: '厥孚交如，威如，吉。' },
      { position: 6, text: '自天佑之，吉无不利。' },
    ],
  },
  {
    id: 15,
    number: 15,
    name: '谦',
    pinyin: 'qiān',
    character: '䷎',
    structure: [0, 0, 1, 0, 0, 0],
    trigrams: { upper: 'kun', lower: 'gen' },
    judgment: '亨，君子有终。',
    image: '地中有山，谦。君子以裒多益寡，称物平施。',
    lines: [
      { position: 1, text: '谦谦君子，用涉大川，吉。' },
      { position: 2, text: '鸣谦，贞吉。' },
      { position: 3, text: '劳谦君子，有终吉。' },
      { position: 4, text: '无不利，撝谦。' },
      { position: 5, text: '不富，以其邻，利用侵伐，无不利。' },
      { position: 6, text: '鸣谦，利用行师，征邑国。' },
    ],
  },
  {
    id: 16,
    number: 16,
    name: '豫',
    pinyin: 'yù',
    character: '䷏',
    structure: [0, 0, 0, 1, 0, 0],
    trigrams: { upper: 'zhen', lower: 'kun' },
    judgment: '利建侯行师。',
    image: '雷出地奋，豫。先王以作乐崇德，殷荐之上帝，以配祖考。',
    lines: [
      { position: 1, text: '鸣豫，凶。' },
      { position: 2, text: '介于石，不终日，贞吉。' },
      { position: 3, text: '盱豫，悔。迟有悔。' },
      { position: 4, text: '由豫，大有得。勿疑。朋盍簪。' },
      { position: 5, text: '贞疾，恒不死。' },
      { position: 6, text: '冥豫，成有渝，无咎。' },
    ],
  },
  {
    id: 17,
    number: 17,
    name: '随',
    pinyin: 'suí',
    character: '䷐',
    structure: [1, 0, 0, 1, 1, 0],
    trigrams: { upper: 'dui', lower: 'zhen' },
    judgment: '元亨利贞，无咎。',
    image: '泽中有雷，随。君子以向晦入宴息。',
    lines: [
      { position: 1, text: '官有渝，贞吉。出门交有功。' },
      { position: 2, text: '系小子，失丈夫。' },
      { position: 3, text: '系丈夫，失小子。随有求得，利居贞。' },
      { position: 4, text: '随有获，贞凶。有孚在道，以明，何咎。' },
      { position: 5, text: '孚于嘉，吉。' },
      { position: 6, text: '拘系之，乃从维之。王用亨于西山。' },
    ],
  },
  {
    id: 18,
    number: 18,
    name: '蛊',
    pinyin: 'gǔ',
    character: '䷑',
    structure: [0, 1, 1, 0, 0, 0],
    trigrams: { upper: 'gen', lower: 'xun' },
    judgment: '元亨，利涉大川。先甲三日，后甲三日。',
    image: '山下有风，蛊。君子以振民育德。',
    lines: [
      { position: 1, text: '干父之蛊，有子，考无咎，厉终吉。' },
      { position: 2, text: '干母之蛊，不可贞。' },
      { position: 3, text: '干父小有晦，无大咎。' },
      { position: 4, text: '裕父之蛊，往见吝。' },
      { position: 5, text: '干父之蛊，用誉。' },
      { position: 6, text: '不事王侯，高尚其事。' },
    ],
  },
  {
    id: 19,
    number: 19,
    name: '临',
    pinyin: 'lín',
    character: '䷒',
    structure: [1, 1, 0, 0, 0, 0],
    trigrams: { upper: 'kun', lower: 'dui' },
    judgment: '元亨利贞。至于八月有凶。',
    image: '泽上有地，临。君子以教思无穷，容保民无疆。',
    lines: [
      { position: 1, text: '咸临，贞吉。' },
      { position: 2, text: '咸临，吉无不利。' },
      { position: 3, text: '甘临，无攸利。既忧之，无咎。' },
      { position: 4, text: '至临，无咎。' },
      { position: 5, text: '知临，大君之宜，吉。' },
      { position: 6, text: '敦临，吉无咎。' },
    ],
  },
  {
    id: 20,
    number: 20,
    name: '观',
    pinyin: 'guān',
    character: '䷓',
    structure: [0, 0, 0, 0, 1, 1],
    trigrams: { upper: 'xun', lower: 'kun' },
    judgment: '盥而不荐，有孚颙若。',
    image: '风行地上，观。先王以省方观民设教。',
    lines: [
      { position: 1, text: '童观，小人无咎，君子吝。' },
      { position: 2, text: '窥观，利女贞。' },
      { position: 3, text: '观我生，进退。' },
      { position: 4, text: '观国之光，利用宾于王。' },
      { position: 5, text: '观我生，君子无咎。' },
      { position: 6, text: '观其生，君子无咎。' },
    ],
  },
  {
    id: 21,
    number: 21,
    name: '噬嗑',
    pinyin: 'shì kè',
    character: '䷔',
    structure: [1, 0, 1, 0, 0, 1],
    trigrams: { upper: 'li', lower: 'zhen' },
    judgment: '亨。利用狱。',
    image: '雷电噬嗑。先王以明罚敕法。',
    lines: [
      { position: 1, text: '屦校灭趾，无咎。' },
      { position: 2, text: '噬肤灭鼻，无咎。' },
      { position: 3, text: '噬腊肉，遇毒，小吝，无咎。' },
      { position: 4, text: '噬乾胏，得金矢，利艰贞，吉。' },
      { position: 5, text: '噬乾肉，得黄金，贞厉，无咎。' },
      { position: 6, text: '何校灭耳，凶。' },
    ],
  },
  {
    id: 22,
    number: 22,
    name: '贲',
    pinyin: 'bì',
    character: '䷕',
    structure: [1, 0, 1, 0, 0, 1],
    trigrams: { upper: 'gen', lower: 'li' },
    judgment: '亨。小利有攸往。',
    image: '山下有火，贲。君子以明庶政，无敢折狱。',
    lines: [
      { position: 1, text: '贲其趾，舍车而徒。' },
      { position: 2, text: '贲其须。' },
      { position: 3, text: '贲如濡如，永贞吉。' },
      { position: 4, text: '贲如皤如，白马翰如，匪寇婚媾。' },
      { position: 5, text: '贲于丘园，束帛戋戋，吝，终吉。' },
      { position: 6, text: '白贲，无咎。' },
    ],
  },
  {
    id: 23,
    number: 23,
    name: '剥',
    pinyin: 'bō',
    character: '䷖',
    structure: [0, 0, 0, 0, 0, 1],
    trigrams: { upper: 'gen', lower: 'kun' },
    judgment: '不利有攸往。',
    image: '山附地上，剥。上以厚下，安宅。',
    lines: [
      { position: 1, text: '剥床以足，蔑贞凶。' },
      { position: 2, text: '剥床以辨，蔑贞凶。' },
      { position: 3, text: '剥之，无咎。' },
      { position: 4, text: '剥床以肤，凶。' },
      { position: 5, text: '贯鱼，以宫人宠，无不利。' },
      { position: 6, text: '硕果不食，君子得舆，小人剥庐。' },
    ],
  },
  {
    id: 24,
    number: 24,
    name: '复',
    pinyin: 'fù',
    character: '䷗',
    structure: [1, 0, 0, 0, 0, 0],
    trigrams: { upper: 'kun', lower: 'zhen' },
    judgment: '亨。出入无疾，朋来无咎。反复其道，七日来复，利有攸往。',
    image: '雷在地中，复。先王以至日闭关，商旅不行，后不省方。',
    lines: [
      { position: 1, text: '不远复，无祗悔，元吉。' },
      { position: 2, text: '休复，吉。' },
      { position: 3, text: '频复，厉无咎。' },
      { position: 4, text: '中行独复。' },
      { position: 5, text: '敦复，无悔。' },
      { position: 6, text: '迷复，凶，有灾眚。用行师，终有大败，以其国君，凶。至于十年，不克征。' },
    ],
  },
  {
    id: 25,
    number: 25,
    name: '无妄',
    pinyin: 'wú wàng',
    character: '䷘',
    structure: [1, 0, 0, 1, 1, 1],
    trigrams: { upper: 'qian', lower: 'zhen' },
    judgment: '元亨利贞。其匪正有眚，不利有攸往。',
    image: '天下雷行，物与无妄。先王以茂对时，育万物。',
    lines: [
      { position: 1, text: '无妄，往吉。' },
      { position: 2, text: '不耕获，不菑畲，则利有攸往。' },
      { position: 3, text: '无妄之灾，或系之牛，行人之得，邑人之灾。' },
      { position: 4, text: '可贞，无咎。' },
      { position: 5, text: '无妄之疾，勿药有喜。' },
      { position: 6, text: '无妄，行有眚，无攸利。' },
    ],
  },
  {
    id: 26,
    number: 26,
    name: '大畜',
    pinyin: 'dà chù',
    character: '䷙',
    structure: [1, 1, 1, 0, 0, 1],
    trigrams: { upper: 'gen', lower: 'qian' },
    judgment: '利贞。不家食，吉。利涉大川。',
    image: '天在山中，大畜。君子以多识前言往行，以畜其德。',
    lines: [
      { position: 1, text: '有厉利已。' },
      { position: 2, text: '舆说輹。' },
      { position: 3, text: '良马逐，利艰贞。曰闲舆卫，利有攸往。' },
      { position: 4, text: '童牛之牿，元吉。' },
      { position: 5, text: '豮豕之牙，吉。' },
      { position: 6, text: '何天之衢，亨。' },
    ],
  },
  {
    id: 27,
    number: 27,
    name: '颐',
    pinyin: 'yí',
    character: '䷚',
    structure: [1, 0, 0, 0, 0, 1],
    trigrams: { upper: 'gen', lower: 'zhen' },
    judgment: '贞吉。观颐，自求口实。',
    image: '山下有雷，颐。君子以慎言语，节饮食。',
    lines: [
      { position: 1, text: '舍尔灵龟，观我朵颐，凶。' },
      { position: 2, text: '颠颐，拂经，于丘颐，征凶。' },
      { position: 3, text: '拂颐，贞凶，十年勿用，无攸利。' },
      { position: 4, text: '颠颐，吉。虎视眈眈，其欲逐逐，无咎。' },
      { position: 5, text: '拂经，居贞吉，不可涉大川。' },
      { position: 6, text: '由颐，厉吉，利涉大川。' },
    ],
  },
  {
    id: 28,
    number: 28,
    name: '大过',
    pinyin: 'dà guò',
    character: '䷛',
    structure: [0, 1, 1, 1, 1, 0],
    trigrams: { upper: 'dui', lower: 'xun' },
    judgment: '栋桡，利有攸往，亨。',
    image: '泽灭木，大过。君子以独立不惧，遁世无闷。',
    lines: [
      { position: 1, text: '藉用白茅，无咎。' },
      { position: 2, text: '枯杨生稊，老夫得其女妻，无不利。' },
      { position: 3, text: '栋桡，凶。' },
      { position: 4, text: '栋隆，吉。有它吝。' },
      { position: 5, text: '枯杨生华，老妇得士夫，无咎无誉。' },
      { position: 6, text: '过涉灭顶，凶，无咎。' },
    ],
  },
  {
    id: 29,
    number: 29,
    name: '坎',
    pinyin: 'kǎn',
    character: '䷜',
    structure: [0, 1, 0, 0, 1, 0],
    trigrams: { upper: 'kan', lower: 'kan' },
    judgment: '习坎，有孚，维心亨，行有尚。',
    image: '水洊至，习坎。君子以常德行，习教事。',
    lines: [
      { position: 1, text: '习坎，入于坎窞，凶。' },
      { position: 2, text: '坎有险，求小得。' },
      { position: 3, text: '来之坎坎，险且枕，入于坎窞，勿用。' },
      { position: 4, text: '樽酒簋贰，用缶，纳约自牖，终无咎。' },
      { position: 5, text: '坎不盈，只既平，无咎。' },
      { position: 6, text: '系用徽纆，置于丛棘，三岁不得，凶。' },
    ],
  },
  {
    id: 30,
    number: 30,
    name: '离',
    pinyin: 'lí',
    character: '䷝',
    structure: [1, 0, 1, 1, 0, 1],
    trigrams: { upper: 'li', lower: 'li' },
    judgment: '利贞，亨。畜牝牛，吉。',
    image: '明两作，离。大人以继明照于四方。',
    lines: [
      { position: 1, text: '履错然，敬之无咎。' },
      { position: 2, text: '黄离，元吉。' },
      { position: 3, text: '日昃之离，不鼓缶而歌，则大耋之嗟，凶。' },
      { position: 4, text: '突如其来如，焚如，死如，弃如。' },
      { position: 5, text: '出涕沱若，戚嗟若，吉。' },
      { position: 6, text: '王用出征，有嘉折首，获其匪丑，无咎。' },
    ],
  },
  {
    id: 31,
    number: 31,
    name: '咸',
    pinyin: 'xián',
    character: '䷞',
    structure: [0, 0, 1, 1, 1, 0],
    trigrams: { upper: 'dui', lower: 'gen' },
    judgment: '亨，利贞，取女吉。',
    image: '山上有泽，咸。君子以虚受人。',
    lines: [
      { position: 1, text: '咸其拇。' },
      { position: 2, text: '咸其腓，凶，居吉。' },
      { position: 3, text: '咸其股，执其随，往吝。' },
      { position: 4, text: '贞吉悔亡，憧憧往来，朋从尔思。' },
      { position: 5, text: '咸其脢，无悔。' },
      { position: 6, text: '咸其辅颊舌。' },
    ],
  },
  {
    id: 32,
    number: 32,
    name: '恒',
    pinyin: 'héng',
    character: '䷟',
    structure: [0, 1, 1, 1, 0, 0],
    trigrams: { upper: 'zhen', lower: 'xun' },
    judgment: '亨，无咎，利贞，利有攸往。',
    image: '雷风，恒。君子以立不易方。',
    lines: [
      { position: 1, text: '浚恒，贞凶，无攸利。' },
      { position: 2, text: '悔亡。' },
      { position: 3, text: '不恒其德，或承之羞，贞吝。' },
      { position: 4, text: '田无禽。' },
      { position: 5, text: '恒其德，贞，妇人吉，夫子凶。' },
      { position: 6, text: '振恒，凶。' },
    ],
  },
  {
    id: 33,
    number: 33,
    name: '遁',
    pinyin: 'dùn',
    character: '䷠',
    structure: [0, 0, 1, 1, 1, 1],
    trigrams: { upper: 'qian', lower: 'gen' },
    judgment: '亨，小利贞。',
    image: '天下有山，遁。君子以远小人，不恶而严。',
    lines: [
      { position: 1, text: '遁尾，厉，勿用有攸往。' },
      { position: 2, text: '执之用黄牛之革，莫之胜说。' },
      { position: 3, text: '系遁，有疾厉，畜臣妾吉。' },
      { position: 4, text: '好遁，君子吉，小人否。' },
      { position: 5, text: '嘉遁，贞吉。' },
      { position: 6, text: '肥遁，无不利。' },
    ],
  },
  {
    id: 34,
    number: 34,
    name: '大壮',
    pinyin: 'dà zhuàng',
    character: '䷡',
    structure: [1, 1, 1, 1, 0, 0],
    trigrams: { upper: 'zhen', lower: 'qian' },
    judgment: '利贞。',
    image: '雷在天上，大壮。君子以非礼弗履。',
    lines: [
      { position: 1, text: '壮于趾，征凶，有孚。' },
      { position: 2, text: '贞吉。' },
      { position: 3, text: '小人用壮，君子用罔，贞厉。羝羊触藩，羸其角。' },
      { position: 4, text: '贞吉悔亡，藩决不羸，壮于大舆之輹。' },
      { position: 5, text: '丧羊于易，无悔。' },
      { position: 6, text: '羝羊触藩，不能退，不能遂，无攸利，艰则吉。' },
    ],
  },
  {
    id: 35,
    number: 35,
    name: '晋',
    pinyin: 'jìn',
    character: '䷢',
    structure: [0, 0, 0, 1, 0, 1],
    trigrams: { upper: 'li', lower: 'kun' },
    judgment: '康侯用锡马蕃庶，昼日三接。',
    image: '明出地上，晋。君子以自昭明德。',
    lines: [
      { position: 1, text: '晋如，摧如，贞吉。罔孚，裕无咎。' },
      { position: 2, text: '晋如，愁如，贞吉。受兹介福，于其王母。' },
      { position: 3, text: '众允，悔亡。' },
      { position: 4, text: '晋如硕鼠，贞厉。' },
      { position: 5, text: '悔亡，失得勿恤，往吉无不利。' },
      { position: 6, text: '晋其角，维用伐邑，厉吉无咎，贞吝。' },
    ],
  },
  {
    id: 36,
    number: 36,
    name: '明夷',
    pinyin: 'míng yí',
    character: '䷣',
    structure: [0, 1, 0, 0, 0, 0],
    trigrams: { upper: 'kun', lower: 'li' },
    judgment: '利艰贞。',
    image: '明入地中，明夷。君子以莅众，用晦而明。',
    lines: [
      { position: 1, text: '明夷于飞，垂其翼。君子于行，三日不食，有攸往，主人有言。' },
      { position: 2, text: '明夷，夷于左股，用拯马壮，吉。' },
      { position: 3, text: '明夷于南狩，得其大首，不可疾贞。' },
      { position: 4, text: '入于左腹，获明夷之心，出于门庭。' },
      { position: 5, text: '箕子之明夷，利贞。' },
      { position: 6, text: '不明晦，初登于天，后入于地。' },
    ],
  },
  {
    id: 37,
    number: 37,
    name: '家人',
    pinyin: 'jiā rén',
    character: '䷤',
    structure: [1, 0, 1, 0, 0, 1],
    trigrams: { upper: 'xun', lower: 'li' },
    judgment: '利女贞。',
    image: '风自火出，家人。君子以言有物，而行有恒。',
    lines: [
      { position: 1, text: '闲有家，悔亡。' },
      { position: 2, text: '无攸遂，在中馈，贞吉。' },
      { position: 3, text: '家人嗃嗃，悔厉吉。妇子嘻嘻，终吝。' },
      { position: 4, text: '富家，大吉。' },
      { position: 5, text: '王假有家，勿恤吉。' },
      { position: 6, text: '有孚威如，终吉。' },
    ],
  },
  {
    id: 38,
    number: 38,
    name: '睽',
    pinyin: 'kuí',
    character: '䷥',
    structure: [1, 0, 1, 1, 0, 1],
    trigrams: { upper: 'li', lower: 'dui' },
    judgment: '小事吉。',
    image: '上火下泽，睽。君子以同而异。',
    lines: [
      { position: 1, text: '悔亡，丧马勿逐，自复。见恶人无咎。' },
      { position: 2, text: '遇主于巷，无咎。' },
      { position: 3, text: '见舆曳，其牛掣，其人天且劓，无初有终。' },
      { position: 4, text: '睽孤，遇元夫，交孚，厉无咎。' },
      { position: 5, text: '悔亡，厥宗噬肤，往何咎。' },
      { position: 6, text: '睽孤，见豕负涂，载鬼一车，先张之弧，后说之弧，匪寇婚媾，往遇雨则吉。' },
    ],
  },
  {
    id: 39,
    number: 39,
    name: '蹇',
    pinyin: 'jiǎn',
    character: '䷦',
    structure: [0, 0, 1, 0, 0, 0],
    trigrams: { upper: 'kan', lower: 'gen' },
    judgment: '利西南，不利东北。利见大人，贞吉。',
    image: '山上有水，蹇。君子以反身修德。',
    lines: [
      { position: 1, text: '往蹇，来誉。' },
      { position: 2, text: '王臣蹇蹇，匪躬之故。' },
      { position: 3, text: '往蹇，来反。' },
      { position: 4, text: '往蹇，来连。' },
      { position: 5, text: '大蹇，朋来。' },
      { position: 6, text: '往蹇，来硕，吉，利见大人。' },
    ],
  },
  {
    id: 40,
    number: 40,
    name: '解',
    pinyin: 'xiè',
    character: '䷧',
    structure: [0, 1, 0, 0, 1, 0],
    trigrams: { upper: 'zhen', lower: 'kan' },
    judgment: '利西南。无所往，其来复吉。有攸往，夙吉。',
    image: '雷雨作，解。君子以赦过宥罪。',
    lines: [
      { position: 1, text: '无咎。' },
      { position: 2, text: '田获三狐，得黄矢，贞吉。' },
      { position: 3, text: '负且乘，致寇至，贞吝。' },
      { position: 4, text: '解而拇，朋至斯孚。' },
      { position: 5, text: '君子维有解，吉。有孚于小人。' },
      { position: 6, text: '公用射隼，于高墉之上，获之，无不利。' },
    ],
  },
  {
    id: 41,
    number: 41,
    name: '损',
    pinyin: 'sǔn',
    character: '䷨',
    structure: [1, 1, 0, 0, 0, 1],
    trigrams: { upper: 'gen', lower: 'dui' },
    judgment: '有孚，元吉，无咎，可贞，利有攸往。曷之用？二簋可用享。',
    image: '山下有泽，损。君子以惩忿窒欲。',
    lines: [
      { position: 1, text: '已事遄往，无咎，酌损之。' },
      { position: 2, text: '利贞，征凶，弗损益之。' },
      { position: 3, text: '三人行，则损一人。一人行，则得其友。' },
      { position: 4, text: '损其疾，使遄有喜，无咎。' },
      { position: 5, text: '或益之，十朋之龟弗克违，元吉。' },
      { position: 6, text: '弗损益之，无咎，贞吉，利有攸往，得臣无家。' },
    ],
  },
  {
    id: 42,
    number: 42,
    name: '益',
    pinyin: 'yì',
    character: '䷩',
    structure: [1, 0, 0, 0, 1, 1],
    trigrams: { upper: 'xun', lower: 'zhen' },
    judgment: '利有攸往，利涉大川。',
    image: '风雷，益。君子以见善则迁，有过则改。',
    lines: [
      { position: 1, text: '利用为大作，元吉，无咎。' },
      { position: 2, text: '或益之，十朋之龟弗克违，永贞吉。王用享于帝，吉。' },
      { position: 3, text: '益之用凶事，无咎。有孚中行，告公用圭。' },
      { position: 4, text: '中行，告公从。利用为依迁国。' },
      { position: 5, text: '有孚惠心，勿问元吉。有孚惠我德。' },
      { position: 6, text: '莫益之，或击之，立心勿恒，凶。' },
    ],
  },
  {
    id: 43,
    number: 43,
    name: '夬',
    pinyin: 'guài',
    character: '䷪',
    structure: [1, 1, 1, 1, 1, 0],
    trigrams: { upper: 'dui', lower: 'qian' },
    judgment: '扬于王庭，孚号，有厉，告自邑，不利即戎，利有攸往。',
    image: '泽上于天，夬。君子以施禄及下，居德则忌。',
    lines: [
      { position: 1, text: '壮于前趾，往不胜为咎。' },
      { position: 2, text: '惕号，莫夜有戎，勿恤。' },
      { position: 3, text: '壮于頄，有凶。君子夬夬，独行遇雨，若濡有愠，无咎。' },
      { position: 4, text: '臀无肤，其行次且。牵羊悔亡，闻言不信。' },
      { position: 5, text: '苋陆夬夬，中行无咎。' },
      { position: 6, text: '无号，终有凶。' },
    ],
  },
  {
    id: 44,
    number: 44,
    name: '姤',
    pinyin: 'gòu',
    character: '䷫',
    structure: [0, 1, 1, 1, 1, 1],
    trigrams: { upper: 'qian', lower: 'xun' },
    judgment: '女壮，勿用取女。',
    image: '天下有风，姤。后以施命诰四方。',
    lines: [
      { position: 1, text: '系于金柅，贞吉，有攸往，见凶，羸豕孚蹢躅。' },
      { position: 2, text: '包有鱼，无咎，不利宾。' },
      { position: 3, text: '臀无肤，其行次且，厉，无大咎。' },
      { position: 4, text: '包无鱼，起凶。' },
      { position: 5, text: '以杞包瓜，含章，有陨自天。' },
      { position: 6, text: '姤其角，吝，无咎。' },
    ],
  },
  {
    id: 45,
    number: 45,
    name: '萃',
    pinyin: 'cuì',
    character: '䷬',
    structure: [0, 0, 0, 1, 1, 0],
    trigrams: { upper: 'dui', lower: 'kun' },
    judgment: '亨。王假有庙，利见大人，亨，利贞。用大牲吉，利有攸往。',
    image: '泽上于地，萃。君子以除戎器，戒不虞。',
    lines: [
      { position: 1, text: '有孚不终，乃乱乃萃，若号一握为笑，勿恤，往无咎。' },
      { position: 2, text: '引吉无咎，孚乃利用禴。' },
      { position: 3, text: '萃如，嗟如，无攸利，往无咎，小吝。' },
      { position: 4, text: '大吉，无咎。' },
      { position: 5, text: '萃有位，无咎。匪孚，元永贞，悔亡。' },
      { position: 6, text: '赍咨涕洟，无咎。' },
    ],
  },
  {
    id: 46,
    number: 46,
    name: '升',
    pinyin: 'shēng',
    character: '䷭',
    structure: [0, 1, 0, 0, 0, 0],
    trigrams: { upper: 'kun', lower: 'xun' },
    judgment: '元亨，用见大人，勿恤，南征吉。',
    image: '地中生木，升。君子以顺德，积小以高大。',
    lines: [
      { position: 1, text: '允升，大吉。' },
      { position: 2, text: '孚乃利用禴，无咎。' },
      { position: 3, text: '升虚邑。' },
      { position: 4, text: '王用亨于岐山，吉无咎。' },
      { position: 5, text: '贞吉，升阶。' },
      { position: 6, text: '冥升，利于不息之贞。' },
    ],
  },
  {
    id: 47,
    number: 47,
    name: '困',
    pinyin: 'kùn',
    character: '䷮',
    structure: [0, 1, 1, 0, 1, 0],
    trigrams: { upper: 'dui', lower: 'kan' },
    judgment: '亨，贞，大人吉，无咎，有言不信。',
    image: '泽无水，困。君子以致命遂志。',
    lines: [
      { position: 1, text: '臀困于株木，入于幽谷，三岁不见。' },
      { position: 2, text: '困于酒食，朱绂方来，利用亨祀，征凶，无咎。' },
      { position: 3, text: '困于石，据于蒺藜，入于其宫，不见其妻，凶。' },
      { position: 4, text: '来徐徐，困于金车，吝，有终。' },
      { position: 5, text: '劓刖，困于赤绂，乃徐有说，利用祭祀。' },
      { position: 6, text: '困于葛藟，于臲卼，曰动悔。有悔，征吉。' },
    ],
  },
  {
    id: 48,
    number: 48,
    name: '井',
    pinyin: 'jǐng',
    character: '䷯',
    structure: [0, 1, 0, 1, 1, 0],
    trigrams: { upper: 'kan', lower: 'xun' },
    judgment: '改邑不改井，无丧无得，往来井井。汔至，亦未繘井，羸其瓶，凶。',
    image: '木上有水，井。君子以劳民劝相。',
    lines: [
      { position: 1, text: '井泥不食，旧井无禽。' },
      { position: 2, text: '井谷射鲋，瓮敝漏。' },
      { position: 3, text: '井渫不食，为我民恻，可用汲，王明，并受其福。' },
      { position: 4, text: '井甃，无咎。' },
      { position: 5, text: '井冽，寒泉食。' },
      { position: 6, text: '井收勿幕，有孚无吉。' },
    ],
  },
  {
    id: 49,
    number: 49,
    name: '革',
    pinyin: 'gé',
    character: '䷰',
    structure: [1, 0, 1, 1, 0, 1],
    trigrams: { upper: 'dui', lower: 'li' },
    judgment: '巳日乃孚，元亨利贞，悔亡。',
    image: '泽中有火，革。君子以治历明时。',
    lines: [
      { position: 1, text: '巩用黄牛之革。' },
      { position: 2, text: '巳日乃革之，征吉，无咎。' },
      { position: 3, text: '征凶，贞厉，革言三就，有孚。' },
      { position: 4, text: '悔亡，有孚改命，吉。' },
      { position: 5, text: '大人虎变，未占有孚。' },
      { position: 6, text: '君子豹变，小人革面，征凶，居贞吉。' },
    ],
  },
  {
    id: 50,
    number: 50,
    name: '鼎',
    pinyin: 'dǐng',
    character: '䷱',
    structure: [0, 1, 1, 1, 0, 1],
    trigrams: { upper: 'li', lower: 'xun' },
    judgment: '元吉，亨。',
    image: '木上有火，鼎。君子以正位凝命。',
    lines: [
      { position: 1, text: '鼎颠趾，利出否，得妾以其子，无咎。' },
      { position: 2, text: '鼎有实，我仇有疾，不我能即，吉。' },
      { position: 3, text: '鼎耳革，其行塞，雉膏不食，方雨亏悔，终吉。' },
      { position: 4, text: '鼎折足，覆公餗，其形渥，凶。' },
      { position: 5, text: '鼎黄耳金铉，利贞。' },
      { position: 6, text: '鼎玉铉，大吉，无不利。' },
    ],
  },
  {
    id: 51,
    number: 51,
    name: '震',
    pinyin: 'zhèn',
    character: '䷲',
    structure: [1, 0, 0, 1, 0, 0],
    trigrams: { upper: 'zhen', lower: 'zhen' },
    judgment: '亨。震来虩虩，笑言哑哑。震惊百里，不丧匕鬯。',
    image: '洊雷，震。君子以恐惧修省。',
    lines: [
      { position: 1, text: '震来虩虩，后笑言哑哑，吉。' },
      { position: 2, text: '震来厉，亿丧贝，跻于九陵，勿逐，七日得。' },
      { position: 3, text: '震苏苏，震行无眚。' },
      { position: 4, text: '震遂泥。' },
      { position: 5, text: '震往来厉，亿无丧，有事。' },
      { position: 6, text: '震索索，视矍矍，征凶。震不于其躬，于其邻，无咎。婚媾有言。' },
    ],
  },
  {
    id: 52,
    number: 52,
    name: '艮',
    pinyin: 'gèn',
    character: '䷳',
    structure: [0, 0, 1, 0, 0, 1],
    trigrams: { upper: 'gen', lower: 'gen' },
    judgment: '艮其背，不获其身，行其庭，不见其人，无咎。',
    image: '兼山，艮。君子以思不出其位。',
    lines: [
      { position: 1, text: '艮其趾，无咎，利永贞。' },
      { position: 2, text: '艮其腓，不拯其随，其心不快。' },
      { position: 3, text: '艮其限，列其夤，厉薰心。' },
      { position: 4, text: '艮其身，无咎。' },
      { position: 5, text: '艮其辅，言有序，悔亡。' },
      { position: 6, text: '敦艮，吉。' },
    ],
  },
  {
    id: 53,
    number: 53,
    name: '渐',
    pinyin: 'jiàn',
    character: '䷴',
    structure: [0, 0, 1, 0, 1, 1],
    trigrams: { upper: 'xun', lower: 'gen' },
    judgment: '女归吉，利贞。',
    image: '山上有木，渐。君子以居贤德，善俗。',
    lines: [
      { position: 1, text: '鸿渐于干，小子厉，有言，无咎。' },
      { position: 2, text: '鸿渐于磐，饮食衎衎，吉。' },
      { position: 3, text: '鸿渐于陆，夫征不复，妇孕不育，凶。利御寇。' },
      { position: 4, text: '鸿渐于木，或得其桷，无咎。' },
      { position: 5, text: '鸿渐于陵，妇三岁不孕，终莫之胜，吉。' },
      { position: 6, text: '鸿渐于陆，其羽可用为仪，吉。' },
    ],
  },
  {
    id: 54,
    number: 54,
    name: '归妹',
    pinyin: 'guī mèi',
    character: '䷵',
    structure: [1, 0, 0, 1, 0, 0],
    trigrams: { upper: 'zhen', lower: 'dui' },
    judgment: '征凶，无攸利。',
    image: '泽上有雷，归妹。君子以永终知敝。',
    lines: [
      { position: 1, text: '归妹以娣，跛能履，征吉。' },
      { position: 2, text: '眇能视，利幽人之贞。' },
      { position: 3, text: '归妹以须，反归以娣。' },
      { position: 4, text: '归妹愆期，迟归有时。' },
      { position: 5, text: '帝乙归妹，其君之袂，不如其娣之袂良，月几望，吉。' },
      { position: 6, text: '女承筐无实，士刲羊无血，无攸利。' },
    ],
  },
  {
    id: 55,
    number: 55,
    name: '丰',
    pinyin: 'fēng',
    character: '䷶',
    structure: [1, 0, 1, 1, 0, 0],
    trigrams: { upper: 'zhen', lower: 'li' },
    judgment: '亨，王假之，勿忧，宜日中。',
    image: '雷电皆至，丰。君子以折狱致刑。',
    lines: [
      { position: 1, text: '遇其配主，虽旬无咎，往有尚。' },
      { position: 2, text: '丰其蔀，日中见斗，往得疑疾，有孚发若，吉。' },
      { position: 3, text: '丰其沛，日中见沫，折其右肱，无咎。' },
      { position: 4, text: '丰其蔀，日中见斗，遇其夷主，吉。' },
      { position: 5, text: '来章，有庆誉，吉。' },
      { position: 6, text: '丰其屋，蔀其家，窥其户，阒其无人，三岁不见，凶。' },
    ],
  },
  {
    id: 56,
    number: 56,
    name: '旅',
    pinyin: 'lǚ',
    character: '䷷',
    structure: [0, 0, 1, 1, 0, 1],
    trigrams: { upper: 'li', lower: 'gen' },
    judgment: '小亨，旅贞吉。',
    image: '山上有火，旅。君子以明慎用刑，而不留狱。',
    lines: [
      { position: 1, text: '旅琐琐，斯其所取灾。' },
      { position: 2, text: '旅即次，怀其资，得童仆贞。' },
      { position: 3, text: '旅焚其次，丧其童仆，贞厉。' },
      { position: 4, text: '旅于处，得其资斧，我心不快。' },
      { position: 5, text: '射雉一矢亡，终以誉命。' },
      { position: 6, text: '鸟焚其巢，旅人先笑后号啕。丧牛于易，凶。' },
    ],
  },
  {
    id: 57,
    number: 57,
    name: '巽',
    pinyin: 'xùn',
    character: '䷸',
    structure: [0, 1, 1, 0, 1, 1],
    trigrams: { upper: 'xun', lower: 'xun' },
    judgment: '小亨，利有攸往，利见大人。',
    image: '随风，巽。君子以申命行事。',
    lines: [
      { position: 1, text: '进退，利武人之贞。' },
      { position: 2, text: '巽在床下，用史巫纷若，吉无咎。' },
      { position: 3, text: '频巽，吝。' },
      { position: 4, text: '悔亡，田获三品。' },
      { position: 5, text: '贞吉悔亡，无不利。无初有终，先庚三日，后庚三日，吉。' },
      { position: 6, text: '巽在床下，丧其资斧，贞凶。' },
    ],
  },
  {
    id: 58,
    number: 58,
    name: '兑',
    pinyin: 'duì',
    character: '䷹',
    structure: [1, 1, 0, 1, 1, 0],
    trigrams: { upper: 'dui', lower: 'dui' },
    judgment: '亨，利贞。',
    image: '丽泽，兑。君子以朋友讲习。',
    lines: [
      { position: 1, text: '和兑，吉。' },
      { position: 2, text: '孚兑，吉，悔亡。' },
      { position: 3, text: '来兑，凶。' },
      { position: 4, text: '商兑，未宁，介疾有喜。' },
      { position: 5, text: '孚于剥，有厉。' },
      { position: 6, text: '引兑。' },
    ],
  },
  {
    id: 59,
    number: 59,
    name: '涣',
    pinyin: 'huàn',
    character: '䷺',
    structure: [0, 1, 0, 0, 1, 1],
    trigrams: { upper: 'xun', lower: 'kan' },
    judgment: '亨。王假有庙，利涉大川，利贞。',
    image: '风行水上，涣。先王以享于帝立庙。',
    lines: [
      { position: 1, text: '用拯马壮，吉。' },
      { position: 2, text: '涣奔其机，悔亡。' },
      { position: 3, text: '涣其躬，无悔。' },
      { position: 4, text: '涣其群，元吉。涣有丘，匪夷所思。' },
      { position: 5, text: '涣汗其大号，涣王居，无咎。' },
      { position: 6, text: '涣其血，去逖出，无咎。' },
    ],
  },
  {
    id: 60,
    number: 60,
    name: '节',
    pinyin: 'jié',
    character: '䷻',
    structure: [1, 1, 0, 0, 1, 0],
    trigrams: { upper: 'kan', lower: 'dui' },
    judgment: '亨。苦节不可贞。',
    image: '泽上有水，节。君子以制数度，议德行。',
    lines: [
      { position: 1, text: '不出户庭，无咎。' },
      { position: 2, text: '不出门庭，凶。' },
      { position: 3, text: '不节若，则嗟若，无咎。' },
      { position: 4, text: '安节，亨。' },
      { position: 5, text: '甘节，吉。往有尚。' },
      { position: 6, text: '苦节，贞凶，悔亡。' },
    ],
  },
  {
    id: 61,
    number: 61,
    name: '中孚',
    pinyin: 'zhōng fú',
    character: '䷼',
    structure: [1, 1, 0, 0, 1, 1],
    trigrams: { upper: 'xun', lower: 'dui' },
    judgment: '豚鱼吉，利涉大川，利贞。',
    image: '泽上有风，中孚。君子以议狱缓死。',
    lines: [
      { position: 1, text: '虞吉，有它不燕。' },
      { position: 2, text: '鸣鹤在阴，其子和之，我有好爵，吾与尔靡之。' },
      { position: 3, text: '得敌，或鼓或罢，或泣或歌。' },
      { position: 4, text: '月几望，马匹亡，无咎。' },
      { position: 5, text: '有孚挛如，无咎。' },
      { position: 6, text: '翰音登于天，贞凶。' },
    ],
  },
  {
    id: 62,
    number: 62,
    name: '小过',
    pinyin: 'xiǎo guò',
    character: '䷽',
    structure: [0, 0, 1, 1, 0, 0],
    trigrams: { upper: 'zhen', lower: 'gen' },
    judgment: '亨，利贞，可小事，不可大事。飞鸟遗之音，不宜上宜下，大吉。',
    image: '山上有雷，小过。君子以行过乎恭，丧过乎哀，用过乎俭。',
    lines: [
      { position: 1, text: '飞鸟以凶。' },
      { position: 2, text: '过其祖，遇其妣。不及其君，遇其臣，无咎。' },
      { position: 3, text: '弗过防之，从或戕之，凶。' },
      { position: 4, text: '无咎，弗过遇之。往厉必戒，勿用永贞。' },
      { position: 5, text: '密云不雨，自我西郊，公弋取彼在穴。' },
      { position: 6, text: '弗遇过之，飞鸟离之，凶，是谓灾眚。' },
    ],
  },
  {
    id: 63,
    number: 63,
    name: '既济',
    pinyin: 'jì jì',
    character: '䷾',
    structure: [1, 0, 1, 0, 1, 0],
    trigrams: { upper: 'kan', lower: 'li' },
    judgment: '亨，小利贞，初吉终乱。',
    image: '水在火上，既济。君子以思患而预防之。',
    lines: [
      { position: 1, text: '曳其轮，濡其尾，无咎。' },
      { position: 2, text: '妇丧其茀，勿逐，七日得。' },
      { position: 3, text: '高宗伐鬼方，三年克之，小人勿用。' },
      { position: 4, text: '繻有衣袽，终日戒。' },
      { position: 5, text: '东邻杀牛，不如西邻之禴祭，实受其福。' },
      { position: 6, text: '濡其首，厉。' },
    ],
  },
  {
    id: 64,
    number: 64,
    name: '未济',
    pinyin: 'wèi jì',
    character: '䷿',
    structure: [0, 1, 0, 1, 0, 1],
    trigrams: { upper: 'li', lower: 'kan' },
    judgment: '亨，小狐汔济，濡其尾，无攸利。',
    image: '火在水上，未济。君子以慎辨物居方。',
    lines: [
      { position: 1, text: '濡其尾，吝。' },
      { position: 2, text: '曳其轮，贞吉。' },
      { position: 3, text: '未济，征凶，利涉大川。' },
      { position: 4, text: '贞吉，悔亡，震用伐鬼方，三年有赏于大国。' },
      { position: 5, text: '贞吉，无悔，君子之光，有孚，吉。' },
      { position: 6, text: '有孚于饮酒，无咎，濡其首，有孚失是。' },
    ],
  },
]

export function getHexagramId(structure: number[]): number {
  let id = 0
  for (let i = 0; i < 6; i++) {
    if (structure[i] === 1) {
      id += Math.pow(2, i)
    }
  }
  return id + 1
}

export function getHexagramById(id: number): Hexagram | undefined {
  return HEXAGRAMS.find((h) => h.id === id)
}

export function getHexagramByName(name: string): Hexagram | undefined {
  return HEXAGRAMS.find((h) => h.name === name)
}

export function getHexagramCharacter(structure: number[]): string {
  const base = 0x4dc0
  const id = getHexagramId(structure) - 1
  return String.fromCodePoint(base + id)
}
